### ISSUE TITLE
Adding a keybind to force building

### ISSUE THREAD

**Issue by Sworddragon** [rezecib/Geometric-Placement#43]
If a buildable structure hovers over another structures that has an action (e.g. hovering a minisign over a fridge or a plank from a boat) the building action vanishes. In the first example above to still place the minisign on the fridge the minisign must hover over a non-fridge area while its placer is still on the same unit as the fridge - which can become easily kind of tricky if other structures like crockpots are being built near and turns out into finding the magic pixel.

This led me to the idea that forcing the building action on buildable units via a keybinding would solve this issue here.

**Comment by rezecib** [comment]
This is unfortunately very difficult to do in any sustainable way. The way the game does this is as follows:

Each action has a type; this determines what situations it can be checked in (for example mousing over ground, mousing over an object, when a particular type of item is equipped, on an item, etc). 

If the type applies, it then runs a function to evaluate whether it's relevant, given what's being moused over, the equipped item, etc.

So in order to disrupt other actions I would need to rewrite large portions of the game code, which actually do change somewhat regularly (which means when they update I still have the old stuff copied and it breaks).

Maybe I'm overlooking a neater way to do this, but it seems more trouble than it's worth at the moment. If someone has an elegant solution here I'd be happy to take a pull request though :)
